### ISSUE TITLE
จัดทำ Change request

### ISSUE THREAD

**Issue by ttipparat** [hongladda/TPBS-CRM#11]
CR1 ปรับโครงสร้างของระบบ Software เดิม 5 เป็น 6 Module --> เกิดจากการวิเคราะห์ของทีมงาน
CR2 ปรับโครงสร้างของระบบ Software เพิ่มจาก 6 Module เป็น 7 Module ตามการประชุมเมื่อวันที่ 19 Feb 2020
CR3 ให้สามารถการเชื่อมโยงกับ๊ Activity ได้
CR4  User ภายใน ขอให้ไม่มีการเชื่อมโยงกับระบบ HRIS

**Comment by RatanapaTis** [comment]
CR1 ปรับโครงสร้างของระบบ Software เดิม 5 Module (ฺBaseline) เป็น 6 Module --> จากการวิเคราะห์ของทีมงาน โดยเพิ่มโมดูล Stakeholder Mapping
CR2 ปรับโครงสร้างของระบบ Software เพิ่มจาก 6 Module เป็น 8 Module ตามที่ประชุมวันพุธที่ 19 ก.พ. 63 โดยเพิ่มโมดูลระบบฐานข้อมูลผู้มีส่วนได้ส่วนเสีย ของ ส.ส.ท. และโมดูลขายและแลกเปลี่ยน
CR3 ระบบ CRM สามารถการเชื่อมโยงกับระบบ Thai PBS Activity Management ได้
CR4 ระบบ CRM ไม่ต้องเชื่อมโยงกับระบบ HRIS เพื่อใช้ข้อมูลผู้ใช้งาน ระบบ CRM ทำการเก็บ และบันทึกข้อมูลผู้ใช้งานในระบบเอง

**Comment by ttipparat** [comment]
จัดทำ CR ส่งให้ลูกค้าลงนามแล้ว
